### ISSUE TITLE
Windowsで地理院タイル目録を完全にダウンロードできない場合がある

### ISSUE THREAD

**Issue by johofukyu** [gsi-cyberjapan/qdltc#1]
ウィルス対策ソフトウェアを導入したWindowsで、ウェブブラウザから地理院タイル目録をダウンロードした場合、ファイルが最後までダウンロードできない場合があるようです。

本レポジトリにある qdltc.rb の問題ではなく、Windows でのファイルのダウンロード方法についての問題ですが、簡便かつ確実にダウンロードする方法をご案内できないか、検討します。

**Comment by hfu** [comment]
この症状は、クライアント又はネットワークのウィルス対策ソフトウェアによるもののようですので、qdltc.rb 側で対応することは困難のようです。情報セキュリティ担当者にご相談いただくのが良いと考えます。
