### ISSUE TITLE
特定のズームレベルのタイルがダウンロードできていない

### ISSUE THREAD

**Issue by mssfj** [gsi-cyberjapan/qdltc#3]
qdltcを利用して標準地図タイルをダウンロードしています。

実行完了したのですが、ズームレベル7,8の一部、18の大半がうまくダウンロードできておりませんでした。再度qdltcを実行してみましたが、やはり一部のタイルはダウンロードできていないようです。目録はhttps://github.com/gsi-cyberjapan/qdltc/wiki/WinStdにあるリンクからダウンロードしたものを利用しています。当方、環境はDebian8.1でrubyのバージョンは2.1.5です。

繰り返しqdltcを実行して取り漏れを埋めていくしかないでしょうか。

また、ダウンロードPCのネット環境は1Gbps光で、CPUはcorei7、メモリ12G、ストレージはSSDを利用してとくにProxyなどは利用していないのですが、ダウンロード速度が平均で50kiB程度です。もう少しqdltcでのダウンロード速度を上げたいのですが、可能でしょうか。

**Comment by johofukyu** [comment]
返信が遅くなり大変申し訳ございません。

うまくダウンロードできていない場合は、繰り返し実行いただくしかないのが現状です。
qdltcを改良いただくことは特に問題ありません。

以上、よろしくお願いいたします。
